run:
	uvicorn workout_api.main:app --host 0.0.0.0 --port 8000 --reload

create-migrations:
	PYTHONPATH=$PYTHONPATH:$(pwd) alembic revision --autogenerate -m "$(d)"

run-migrations:
	PYTHONPATH=$PYTHONPATH:$(pwd) alembic upgrade head