"""fix relation clients and transactions bugs 6

Revision ID: 43a3ae8aa4ed
Revises: af15d37c3202
Create Date: 2025-11-07 15:40:43.466643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a3ae8aa4ed'
down_revision: Union[str, Sequence[str], None] = 'af15d37c3202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
