"""update database table

Revision ID: 69899715ad2b
Revises: 8ccf471640a2
Create Date: 2025-11-06 16:13:42.336943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69899715ad2b'
down_revision: Union[str, Sequence[str], None] = '8ccf471640a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_agencia'), table_name='accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_agencia'), 'accounts', ['agencia'], unique=True)
    # ### end Alembic commands ###
