"""

Revision ID: 7d300428f65d
Revises: f52df9484369
Create Date: 2025-11-07 14:55:20.012942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d300428f65d'
down_revision: Union[str, Sequence[str], None] = 'f52df9484369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('client_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('transactions_account_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'clients', ['client_id'], ['id'])
    op.drop_column('transactions', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_account_id_fkey'), 'transactions', 'accounts', ['account_id'], ['id'])
    op.drop_column('transactions', 'client_id')
    # ### end Alembic commands ###
