"""fix relation clients and transactions bugs 5

Revision ID: af15d37c3202
Revises: b4439f1c39fd
Create Date: 2025-11-07 15:36:13.706319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af15d37c3202'
down_revision: Union[str, Sequence[str], None] = 'b4439f1c39fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
