"""fix relation clients and transactions bugs 4

Revision ID: b4439f1c39fd
Revises: d1d772da1cbb
Create Date: 2025-11-07 15:29:40.041863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4439f1c39fd'
down_revision: Union[str, Sequence[str], None] = 'd1d772da1cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
