"""alterando uuid de transacoes para id integer

Revision ID: b56954cb89ea
Revises: 9b6748f82cee
Create Date: 2025-11-08 15:43:17.332815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56954cb89ea'
down_revision: Union[str, Sequence[str], None] = '9b6748f82cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
